version: "3.8"
services:
  mongo:
    image: mongo:6
    restart: unless-stopped
    ports:
      - "27018:27017"
    volumes:
      - mongo-data:/data/db

  api:
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      - mongo
    ports:
      - "8080:80"
    # environment:
    #   - MongoSettings__ConnectionString=mongodb://mongo:27017
    #   - MongoSettings__DatabaseName=million_realestate
    env_file:
      - .env
    environment:
      - ASPNETCORE_URLS=http://+:80

volumes:
  mongo-data:
